### PR TITLE
Styling plugins list

### PR DESCRIPTION
**Pull request by fmoliveira**
I'm now working to style the plugins list. Still have to style the script block and dependencies list.

You may already merge if you want, I can send a new pull request for styling the rest of it. :smiley: 

Screenshot

### CODE REVIEW

**Comment by deusprogrammer** [comment]
Merged =)

**Comment by deusprogrammer** [comment]
Also wanted to mention that the api provides for pagination now.  We just need to modify the view plugins page to handle it.  The total record count is returned in the "record-count" header.

**Comment by deusprogrammer** [comment]
Also, show script seems to be broken =(.  It seems to be trying to run the script.

**Comment by fmoliveira** [comment]
Sure. I've really noticed something weird with the show script button. I've opened issue #3 to handle it.

I've also opened issue #4 to add support for pagination. :+1:

**Pull request merged**
